apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: mlflowmodels.mlflow.nizepart.com
spec:
  group: mlflow.nizepart.com
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                modelName:
                  type: string
                modelAlias:
                  type: string
                monitoringInterval:
                  type: integer
                minioSecret:
                  type: string
            status:
              type: object
              properties:
                currentModelVersion:
                  type: string
                  description: "Current model version"
                previousModelVersion:
                  type: string
                  description: "Previous model version"
                error:
                  type: string
                  description: "Error info"
      subresources:
        status: {}
  scope: Namespaced
  names:
    plural: mlflowmodels
    singular: mlflowmodel
    kind: MlflowModel
    shortNames:
      - mlflowm
